version: '3'

services:

  server:
    build: .
    container_name: server
    image: yuttasakcom/nodejs-docker:1.0.0
    volumes:
      - ./src:/src
    ports:
      - "3000:3000"
    restart: always
